commands/MHELP.md, server/commands/adapted.backend.js, server/commands/adapted.command.js, server/commands/set.backend.js
toggle 'Currently Adapted' role
Mod/admin only
set schedule [napchart] delete role
=> [ADD] adapted command

commands/MHELP.md, server/commands/adapted.backend.js, server/commands/adapted.command.js
`+adapted [schedule] username`
add the Adapted-schedule role and delete the Attempted-schedule one
if schedule isn't provided, add the Currently Adapted and get the schedule from the DB
=> UPDATE adapted command

commands/help/jetlag.md
Changed wording, updated info and changed title
=> travelling.md

commands/DC1.md, commands/HELP.2.md, commands/MHELP.md, commands/help/jetlag.md, server/commands/adapted.backend.js, server/commands/tg.backend.js, server/commands/tg.command.js
take the good schedule from database
fix bug about building instance and saving schedule if the schedule is given in the command
modifier fixed when the schedule is taken from the DB
=> UPDATE MHELP and adapted command

commands/HELP.2.md, commands/MHELP.md, server/commands/adapted.backend.js, server/commands/events.command.js, server/commands/focus.command.js, server/commands/set.backend.js, server/commands/tg.backend.js, server/commands/tg.command.js, server/commands/unfocus.command.js, server/models/focus.model.js
Fix on the adapted function (error message and wrong user variable)
Update of tg functions, now a function which toggle one role is available
Add the focus and unfocus function
Add the toggleevent function, to toggle the Events role
=> FIX + Focus Function

server/commands/focus.command.js, server/commands/unfocus.command.js
display the good day now
focus and unfocus displayed in others channel as well, so people can see them
=> FIX on focus

commands/help/underage.md
Note <#257401368807997440> makes a clickable link to the channel.
=> Fixed botspam channel name

commands/HELP.2.md, commands/help/help.md, commands/help/os.md, commands/help/oss.md
(The help message is still less than 2000 characters.)
=> Added a line for `+nc <url>` Edit: and OS --> OSS

commands/MHELP.md, server/command.ctrl.js, server/commands/focus.command.js, server/commands/unfocus.command.js, server/commands/updatereport.command.js
=> UPDATE report generate json file

commands/HELP.2.md, server/commands/marketplace.command.js
Run +togglemarketplace to get added to or removed from the marketplace role
=> Add togglemarketplace command

server/commands/set.backend.js
when the report is not created, value is null and thus don't have subvalue
=> FIX set report model not created

server/commands/focus.command.js, server/commands/unfocus.command.js
days for unfocus were off for a few days
spelling mistakes
permission added. now focus hide all channel, unfocus invert it
=> UPDATE / FIX focus and unfocus

server/commands/unfocus.command.js
also delete last bot message after 5 seconds
will delete all message from the user as well as all bot message (no matter what is it
don't use bulk as it's copy an old function
newt napgod will use buld
=> ADD delete message upon unfocus

config.json.sample, server/commands/updatereport.command.js
document was assumed to be in the db, which isn't the case at first try, and if there's some bug
a tad ugly but as v3 is coming, no need to lose time on refactor for a small thing
=> FIX report when missing document in db

server/commands/schedules.js
bix is an abbreviation for biphasicx
name will have a - later : Biphasic-X and maybe be case sensitive, but in a later update
=> ADD schedules qc0 and biphasicx

server/commands/get.command.js
=> FIX time display for get, time < 1h

commands/LOGHELP.md, server/commands/freelog.dm.js, server/commands/log.dm.js, server/commands/log.tools.js, server/commands/logeeg.dm.js
Fix moods displaying the scores, which made the diff formatting bug.
Fix roles assignment, checking previously existing ones.
Avoid using full comparison for role checking.
=> log: fix moods diff and roles

server/commands/updatereport.command.js
reportDiscord.json is a report filtering only the user on the Discord server. It is made for data exploitation purpose
=> ADD reportDiscord.json - only user on the server

server/commands/get.command.js
createdAt is the date when the user was entered in the DB
=> FIX get schedule time was wrong

server/commands/userinfo.command.js
the join position is not the same everytime
may be because of the array being updated, but not sure
trying clone to fix
=> FIX position unstable. Not sure

server/commands/log.dm.js
=> log: fix abort during steps explanation

commands/LOGHELP.md, server/commands/freelog.dm.js, server/commands/log.dm.js, server/commands/logoption.command.js, server/commands/napchart.js, server/commands/set.backend.js, server/models/log.model.js, server/models/user.model.js
Feats:
- `+log`: Add storing of segments in the db (cores/naps descriptions)
- `+log`: Order cores from 8pm onward
- `+log`: Add options to make logging faster
- `+logoption`: Add `+logoption` command to manage options for logging
- `+set`: Store sleeps
- `+log`: Store sleeps
Fixes:
- Manage big logs by splitting into multiple embeds / fields
- Make log and freelog safer for users (will not block users on crash)
- Clean up code a bit
- Skip the first question that wasn't that useful (confirm from db)
- Combine the first message with the second one
Document some functions.
=> Feats log / options and set

commands/HELP.md, server/commands/history.command.js
- `+history` lists, in reverse order, all the schedules that a user has attempted and when they adapted to it, while merging consecutive failed attempts to save space.
- `+historyfull` lists, in reverse order, all the schedules that a user has attempted, without any processing.
=> Add history commands

server/commands/adapted.command.js
Removes some androcentric wording
=> Grammar fix

config.json.sample, server/commands/create.command.js, server/commands/exportlogs.command.js, server/commands/get.command.js, server/commands/getstatus.command.js, server/commands/mset.backend.js, server/commands/mset.command.js, server/commands/napchart.js, server/commands/print.command.js, server/commands/rebuild.command.js, server/commands/set.backend.js, server/commands/set.command.js, server/commands/updatereport.command.js, server/imageCache.js
-Fixed +set, +status, +nc, and +create commands so that they work with the latest Napchart functionality.
-Modified a few variables and names to improve consistency in codebase and presentation.
=> Napchart command fixes
